name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 显式赋予对内容的写权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 使用更新后的v3版本

      - name: Setup Node.js
        uses: actions/setup-node@v4  # 使用更新后的v4版本
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Get package version
        id: get_version
        run: echo "PACKAGE_VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release
        uses: actions/create-release@v1  # 正确使用v1版本
        with:
          tag_name: "v${{ env.PACKAGE_VERSION }}"
          release_name: "Release v${{ env.PACKAGE_VERSION }}"
          body: |
            Automatic release based on changes in v${{ env.PACKAGE_VERSION }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
